# Generated by Django 5.1.1 on 2024-10-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_title', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='header_img/%y.%m.%d')),
                ('created_at', models.DateField(auto_now=True)),
                ('creat_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
