# Generated by Django 5.1.1 on 2024-10-09 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_model_brand_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['selling_count', 'price', 'rating'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('Availability', 'Availability'), ('Unavailabile', 'Unavailabile')], default='Availability', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview_large',
            field=models.ImageField(blank=True, null=True, upload_to='products/products_img/preview/large/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview_medium',
            field=models.ImageField(blank=True, null=True, upload_to='products/products_img/preview/medium/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/products_img/preview/small/'),
        ),
        migrations.AddField(
            model_name='product',
            name='producte_tags',
            field=models.TextField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('s', 's'), ('l', 'l'), ('xs', 'xs'), ('xl', 'xl'), ('m', 'm')], default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/products_img'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='Main_Brand',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
                'db_table': 'Main_Category',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
    ]
