# Generated by Django 5.1.1 on 2024-10-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_model_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[(True, 'Availability'), (False, 'Unavailabile')], default='Availability', max_length=30),
        ),
    ]
