# Generated by Django 5.1.1 on 2024-10-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(choices=[(True, 'Availability'), (False, 'Unavailabile')], default=True),
        ),
    ]
