# Generated by Django 5.1.1 on 2024-10-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_product_availability_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[(True, 'Availability'), (False, 'Unavailabile')], default='Availability', max_length=30),
        ),
    ]
