# Generated by Django 5.1.1 on 2024-10-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_product_available_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Unavailable')], default=True),
        ),
    ]
