# Generated by Django 5.1.1 on 2024-10-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'Availability'), ('unavailable', 'Unavailabile')], default='Availability', max_length=30),
        ),
    ]
