# Generated by Django 5.1.1 on 2024-10-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('WHITE', 'WHITE')], max_length=15),
        ),
    ]
