# Generated by Django 5.1.1 on 2024-10-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black')], max_length=15),
        ),
    ]
