# Generated by Django 5.1.1 on 2024-10-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_brand_img_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='whishlist',
            new_name='wishlist',
        ),
    ]
