# Generated by Django 5.1.1 on 2024-10-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_whishlist_product_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
