# Generated by Django 5.1.1 on 2024-10-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_product_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wishlist',
            new_name='whishlist',
        ),
    ]
