# Generated by Django 5.1.1 on 2024-10-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_rename_wishlist_product_whishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='whishlist',
        ),
    ]
