# Generated by Django 5.1.1 on 2024-10-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_product_whishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
