# Generated by Django 5.1.1 on 2024-10-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
    ]
