# Generated by Django 5.1.1 on 2024-10-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_product_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
